<Project Sdk="Microsoft.NET.Sdk.Worker">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Restaurantes.Messaging.RabbitMq\Restaurantes.Messaging.RabbitMq.csproj" />
    <ProjectReference Include="..\Restaurantes.Payments.Contracts\Restaurantes.Payments.Contracts.csproj" />
    <ProjectReference Include="..\Restaurantes.Payments.Infrastructure\Restaurantes.Payments.Infrastructure.csproj" />
  </ItemGroup>
</Project>
