receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  transform/add-service-name:
    metric_statements:
      - context: datapoint
        statements:
          - set(attributes["service_name"], resource.attributes["service.name"])

exporters:
  prometheus:
    endpoint: 0.0.0.0:9464

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [transform/add-service-name]
      exporters: [prometheus]
