// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Restaurantes.Dining.Api.Write;

#nullable disable

namespace Restaurantes.Dining.Api.Write.Migrations
{
    [DbContext(typeof(DiningDbContext))]
    partial class DiningDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Restaurantes.Dining.Api.Write.DiningInboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("Restaurantes.Dining.Api.Write.DiningPendingPayment", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OrderId");

                    b.ToTable("pending_payments", (string)null);
                });

            modelBuilder.Entity("Restaurantes.Dining.Api.Write.DiningRestaurantPolicy", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowCheckoutBeforeKitchenCompletion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("QrAllowedNetworks")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("QrRequiresImmediatePayment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("RequireTrustedNetworkForQr")
                        .HasColumnType("boolean");

                    b.Property<bool>("TakeawayRequiresPrepayment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("RestaurantId");

                    b.ToTable("dining_restaurant_policies", (string)null);
                });

            modelBuilder.Entity("Restaurantes.Dining.Api.Write.DiningSession", b =>
                {
                    b.Property<bool>("RequestGuestCount").HasColumnType("boolean");
                    b.Property<int?>("GuestCount").HasColumnType("integer");
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CancellationReason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CancelledByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CheckoutIdempotencyKey")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerAccessToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("OpenedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TableId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TableId", "Status")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Open'");

                    b.ToTable("dining_sessions", (string)null);
                });

            modelBuilder.Entity("Restaurantes.Dining.Api.Write.DiningSessionOrder", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("DiningSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OrderId");

                    b.HasIndex("DiningSessionId");

                    b.ToTable("dining_session_orders", (string)null);
                });

            modelBuilder.Entity("Restaurantes.Dining.Api.Write.DiningZone", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<Guid>("RestaurantId").HasColumnType("uuid");
                    b.Property<string>("Name").IsRequired().HasMaxLength(80).HasColumnType("character varying(80)");
                    b.Property<int>("SortOrder").HasColumnType("integer");
                    b.HasKey("Id");
                    b.HasAlternateKey("RestaurantId", "Id");
                    b.Property<DateTime?>("DeletedAtUtc").IsConcurrencyToken().HasColumnType("timestamp with time zone");
                    b.HasIndex("RestaurantId", "Name").IsUnique().HasFilter("\"DeletedAtUtc\" IS NULL");
                    b.ToTable("dining_zones", (string)null);
                });
            modelBuilder.Entity("Restaurantes.Dining.Api.Write.RestaurantTable", b =>
                {
                    b.Property<bool>("RequestGuestCount").HasColumnType("boolean");
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QrCode")
                        .IsUnique();

                    b.HasIndex("RestaurantId", "Code")
                        .IsUnique()
                        .HasFilter("\"DeletedAtUtc\" IS NULL");

                    b.Property<DateTime?>("DeletedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<Guid>("ZoneId").HasColumnType("uuid");
                    b.HasIndex("RestaurantId", "ZoneId");
                    b.ToTable("restaurant_tables", (string)null);
                });

            modelBuilder.Entity("Restaurantes.Dining.Api.Write.DiningSession", b =>
                {
                    b.HasOne("Restaurantes.Dining.Api.Write.RestaurantTable", null)
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Restaurantes.Dining.Api.Write.DiningSessionOrder", b =>
                {
                    b.HasOne("Restaurantes.Dining.Api.Write.DiningSession", null)
                        .WithMany("Orders")
                        .HasForeignKey("DiningSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Restaurantes.Dining.Api.Write.DiningSession", b =>
                {
                    b.Navigation("Orders");
                });
            modelBuilder.Entity("Restaurantes.Dining.Api.Write.RestaurantTable", b =>
                {
                    b.HasOne("Restaurantes.Dining.Api.Write.DiningZone", "Zone")
                        .WithMany()
                        .HasForeignKey("RestaurantId", "ZoneId")
                        .HasPrincipalKey("RestaurantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.Navigation("Zone");
                });
#pragma warning restore 612, 618
        }
    }
}
