<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>952599ba-cfcf-45fd-ae22-3646f852f75d</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Restaurantes.Identity.Application\Restaurantes.Identity.Application.csproj" />
    <ProjectReference Include="..\Restaurantes.Identity.Infrastructure\Restaurantes.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Restaurantes.ServiceDefaults\Restaurantes.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Restaurantes.Security\Restaurantes.Security.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference
      Include="Microsoft.AspNetCore.Authentication.OpenIdConnect"
      Version="10.0.11"
    />
  </ItemGroup>
</Project>
