// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Restaurantes.Reporting.Infrastructure;
using Restaurantes.Reporting.Infrastructure.Persistence.Read;

#nullable disable

namespace Restaurantes.Reporting.Infrastructure.Migrations
{
    [DbContext(typeof(ReportingReadDbContext))]
    [Migration("20260829165118_InitialReportingRead")]
    partial class InitialReportingRead
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Restaurantes.Reporting.Infrastructure.DeliveredOrderFact", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DeliveredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LinesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PaymentTiming")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("Total")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("RestaurantId", "DeliveredAtUtc");

                    b.ToTable("delivered_order_facts", (string)null);
                });

            modelBuilder.Entity("Restaurantes.Reporting.Infrastructure.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("inbox_messages", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
