<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Restaurantes.Payments.Contracts\Restaurantes.Payments.Contracts.csproj" />
    <ProjectReference Include="..\Restaurantes.Payments.Domain\Restaurantes.Payments.Domain.csproj" />
  </ItemGroup>
</Project>
