<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Restaurantes.RestaurantOperations.Contracts\Restaurantes.RestaurantOperations.Contracts.csproj" />
    <ProjectReference Include="..\Restaurantes.RestaurantOperations.Domain\Restaurantes.RestaurantOperations.Domain.csproj" />
  </ItemGroup>
</Project>
